  - name: "cliphist"
    
  - name: "grim"
    
  - name: "hyprland"
    
  - name: "kitty"
    
  - name: "less"
    
  - name: "rofi"

  - name: "slurp"

  - name: "waybar"

  - name: "noto-fonts-emoji"

  - name: "ttf-jetbrains-mono"

  - name: "ttf-nerd-fonts-symbols-mono"

  - name: "ttf-roboto"

  - name: "networkmanager"
    setupCommands:
      - 'systemctl enable NetworkManager'
  
  - name: "pipewire-pulse"
    setupCommands:
      - 'sudo -u "$SUDO_USER" -i bash -c "systemctl --user enable pipewire pipewire-pulse"'
      
  - name: "wireplumber"
    setupCommands:
      - 'sudo -u "$SUDO_USER" -i bash -c "systemctl --user enable wireplumber"'

  - name: "swww"
    setupCommands:
      - 'sudo -u "$SUDO_USER" -i bash -c "swww-daemon"'
      
  - name: "xdg-desktop-portal-hyprland"
    setupCommands:
      - 'sudo -u "$SUDO_USER" -i bash -c "systemctl --user enable xdg-desktop-portal-hyprland.service"'

  - name: "fish"
    setupCommands:
      - 'sudo -u "$SUDO_USER" -i bash -c "chsh /usr/bin/fish"'