pacman:
  - name: 'cliphist'

  - name: 'mako'

  - name: 'grim'

  - name: 'hyprland'

  - name: 'kitty'

  - name: 'less'

  - name: 'rofi'

  - name: 'slurp'

  - name: 'waybar'

  - name: 'ttf-roboto'

  - name: 'ttf-nerd-fonts-symbols-mono'

  - name: 'swww'

  - name: 'ttf-jetbrains-mono'

  - name: 'noto-fonts-emoji'

  - name: 'xdg-desktop-portal-hyprland'
    setupCommands:
      - command: 'systemctl --user enable --now xdg-desktop-portal-hyprland.service'
        root: false

  - name: 'pipewire-pulse'
    setupCommands:
      - command: 'systemctl --user enable --now pipewire pipewire-pulse'
        root: false

  - name: 'wireplumber'
    setupCommands:
      - command: 'systemctl --user enable --now wireplumber'
        root: false

  - name: 'networkmanager'
    setupCommands:
      - command: 'systemctl enable --now NetworkManager'
        root: true

  - name: 'fish'
    setupCommands:
      - command: 'chsh -s /usr/bin/fish $SUDO_USER'
        root: true


hyprplugins: 
  - name: 'Hyprspace'
    repository: 'https://github.com/KZDKM/Hyprspace'
    buildDependencies:
      pacman:
        - name: 'cpio'
        - name: "cmake"
        - name: "git"
        - name: "meson"
        - name: "gcc"


additionalUtils: 
  - name: 'TinyFetch'
    buildDependencies:
      pacman:
        - name: 'curl'
    setupCommands:
      - command: 'curl -L https://github.com/AnvilM/tinyfetch/releases/latest/download/tinyfetch -o tinyfetch && chmod +x tinyfetch && mv tinyfetch /usr/bin/'
        root: true
    
  - name: 'yay'
    buildDependencies:
      pacman:
        - name: 'git'
        - name: 'base-devel'
    setupCommands:
      - command: 'git clone "https://aur.archlinux.org/yay.git"'
        root: false

      - command: 'makepkg -s -c -i -D ./yay'
        root: true

      - command: 'rm -rf ./yay'
        root: true


assets:
  scripts:
    # Scripts
    - "assets/.rice/scripts/screenshot.sh"

    # Rofi
    - "assets/.rice/rofi/cliphist/cliphist.sh"
    - "assets/.rice/rofi/launcher/launcher.sh"
    - "assets/.rice/rofi/screenshot/screenshot.sh"
    - "assets/.rice/rofi/wallpaper/wallpaper.sh"

    # Notifications
    - "assets/.rice/notifications/battery/battery.sh"
    - "assets/.rice/notifications/error/error.sh"
    - "assets/.rice/notifications/screenshot/screenshot.sh"