pacman:
  - name: 'cliphist'

  - name: 'mako'

  - name: 'grim'

  - name: 'hyprland'

  - name: 'kitty'

  - name: 'less'

  - name: 'rofi'

  - name: 'slurp'

  - name: 'waybar'

  - name: 'ttf-roboto'

  - name: 'ttf-nerd-fonts-symbols-mono'

  - name: 'ttf-jetbrains-mono'

  - name: 'noto-fonts-emoji'

  - name: 'xdg-desktop-portal-hyprland'
    setupCommands:
      - 'sudo -u "$SUDO_USER" -i sh -c "systemctl --user enable --now xdg-desktop-portal-hyprland.service"'

  - name: 'pipewire-pulse'
    setupCommands:
      - 'sudo -u "$SUDO_USER" -i sh -c "systemctl --user enable --now pipewire pipewire-pulse"'

  - name: 'wireplumber'
    setupCommands:
      - 'sudo -u "$SUDO_USER" -i sh -c "systemctl --user enable --now wireplumber"'

  - name: 'networkmanager'
    setupCommands:
      - 'systemctl enable --now NetworkManager'

  - name: 'swww'
    setupCommands:
      - 'sudo -u "$SUDO_USER" -i sh -c "swww-daemon"'

  - name: 'fish'
    setupCommands:
      - 'sudo -u "$SUDO_USER" -i sh -c "chsh -s /usr/bin/fish"'


hyprplugins: 
  - name: 'Hyprspace'
    repository: 'https://github.com/KZDKM/Hyprspace'
    buildDependencies:
      pacman:
        - name: 'cpio'
        - name: "cmake"
        - name: "git"
        - name: "meson"
        - name: "gcc"


additionalUtils: 
  - name: 'TinyFetch'
    buildDependencies:
      pacman:
        - name: 'curl'
    setupCommands:
      - 'curl -L https://github.com/AnvilM/tinyfetch/releases/latest/download/tinyfetch -o tinyfetch && chmod +x tinyfetch && mv tinyfetch /usr/bin/'
    
  - name: 'yay'
    buildDependencies:
      pacman:
        - name: 'git'
        - name: 'base-devel'
    setupCommands:
      - 'sudo -u "$SUDO_USER" -i sh -c "git clone https://aur.archlinux.org/yay.git"'
      - 'sudo -u "$SUDO_USER" -i sh -c "makepkg -s -c -i -D ./yay"'
      - 'rm -rf ./yay'


assets:
  scripts:
    # Scripts
    - "assets/.rice/scripts/screenshot.sh"

    # Rofi
    - "assets/.rice/rofi/cliphist/cliphist.sh"
    - "assets/.rice/rofi/launcher/launcher.sh"
    - "assets/.rice/rofi/screenshot/screenshot.sh"
    - "assets/.rice/rofi/wallpaper/wallpaper.sh"

    # Notifications
    - "assets/.rice/notifications/battery/battery.sh"
    - "assets/.rice/notifications/error/error.sh"
    - "assets/.rice/notifications/screenshot/screenshot.sh"